# Generated by Django 2.0.5 on 2018-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.CharField(default='do some homework', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
